### PR TITLE
Basic UI

### PR DESCRIPTION
**Pull request by pinkmoon25**
### school library: add basic UI

- Made ruby file executable to run in console
- Created App class with following methods:

  -   List all books.
  -   List all people.
  -   Create a person (teacher or student, not a plain Person).
  -   Create a book.
  -   Create a rental.
  -   List all rentals for a given person id.
 

- Created main.rb file to serve as an entry point for the app
- Defined main method to do the following:

  - present the user with a list of options to perform.
  - Lets users choose an option.
  - If needed, ask for parameters for the option.
  - Have a way to quit the app.

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi @PinkMoon25, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [x] Please I am unable to run your app from my end, please make sure your app is running according to the project [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_ui.md), and also please it will be nice to add a `setup section` with `explicit steps` to clone and run your app locally, as this will be of help to none technical users who would like to know how your app works. Kindly add steps to clone and run your app locally. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pinkmoon25** [comment]
I updated the instruction so you can run the code locally

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @PinkMoon25 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pinkmoon25** [comment]
Thank you @emmanuellekamwa for the review :+1:

**Pull request merged**
